OPENAI_API_KEY = ""
CHATGPT_MODEL = "gpt-3.5-turbo"
SYSTEM_MESSAGE = ""
TELEGRAM_API_ID = ""
TELEGRAM_API_HASH = ""
TELEGRAM_PHONE = ""
TELEGRAM_USERNAME = ""
TELEGRAM_CHANNEL_URLS = ["https://t.me/example"]